name: Windows RDP Access

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Enable RDP
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1

      - name: Create new user
        run: |
          $password = ConvertTo-SecureString "ComplexP@ssw0rd123" -AsPlainText -Force
          New-LocalUser -Name "newuser" -Password $password -FullName "New User" -Description "RDP User"
          Add-LocalGroupMember -Group "Administrators" -Member "newuser"

      - name: Download Serveo script
        run: Invoke-WebRequest -Uri https://serveo.net -OutFile serveo.ps1

      - name: Start Serveo tunnel
        run: |
          Start-Process powershell -ArgumentList '-NoProfile -ExecutionPolicy Bypass -File serveo.ps1 -RDP 3389'
